frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use Mpdf\Mpdf;
use Mpdf\Output\Destination;
use Yii;
use yii\web\Controller;
use yii\web\ErrorAction;
use yii\web\HttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
                'layout' => 'error',
            ],
        ];
    }

    public function actionIndex(): string
    {
        return $this->render('index');
    }

    public function actionSkills(): string
    {
        return $this->render('skills');
    }

    public function actionProjects(): string
    {
        return $this->render('projects');
    }

    public function actionContact(): string
    {
        return $this->render('contact');
    }

    public function actionExperience(): string
    {
        return $this->render('experience');
    }

    public function actionFaq(): string
    {
        return $this->render('faq');
    }

    public function actionCv(): string
    {
        $this->layout = 'cv';
        return $this->render('cv');
    }

    /**
     * @return \yii\web\Response
     * @throws HttpException
     */
    public function actionDownload(): \yii\web\Response
    {
        try {
            $mPDF = new Mpdf(['tempDir' => Yii::getAlias('@frontend/runtime/mpdf')]);
            $this->layout = 'cv';
            $view = $this->render('cv');
            $mPDF->WriteHTML($view);
            return Yii::$app->response->sendContentAsFile(
                $mPDF->Output('luka-camernik-cv.pdf', Destination::STRING_RETURN),
                'luka-camernik-cv.pdf'
            );
        } catch (\Exception $e) {
            throw new HttpException('503', 'There was an issue generating PDF file, please try back later');
        }
    }
}

frontend/views/layouts/cv.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use frontend\assets\CVAsset;
use yii\helpers\Html;

CVAsset::register($this);
$metaDescription = 'CV of Luka Dobrota Camernik.';
$metaTitle = 'PHP Backend Developer';
$metaImage = 'https://luka.camernik.com/img/luka.jpg';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" prefix="og: http://ogp.me/ns#">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>

    <?php /* META */ ?>
    <meta name="description" content="<?= $metaDescription ?>"/>
    <meta property="og:locale" content="en_GB"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://luka.camernik.com"/>
    <meta property="og:title" content="<?= $metaTitle ?>"/>
    <meta property="og:description" content="<?= $metaDescription ?>"/>
    <meta property="og:image" content="<?= $metaImage ?>"/>
    <meta property="og:image:width" content="288"/>
    <meta property="og:image:height" content="294"/>
    <?php /* END OF META */ ?>
    <?php /* FAVICON */ ?>
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/favicon/manifest.json">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    <?php /* END OF FAVICON */ ?>

	<?php $this->head() ?>
</head>
<body class="top">
<?php $this->beginBody() ?>

<?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/error.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);

// This variables repeat within the meta tags since some of them are for Facebook, OpenGraph and twitter cards.
$metaDescription = 'Portfolio and CV of Luka Dobrota Camernik.';
$metaTitle = 'PHP Backend Developer';
$metaImage = 'https://luka.camernik.com/img/luka.jpg';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" prefix="og: http://ogp.me/ns#">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>

    <?php /* META */ ?>
    <meta name="description" content="<?= $metaDescription ?>"/>
    <meta property="og:locale" content="en_GB"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://luka.camernik.com"/>
    <meta property="og:title" content="<?= $metaTitle ?>"/>
    <meta property="og:description" content="<?= $metaDescription ?>"/>
    <meta property="og:image" content="<?= $metaImage ?>"/>
    <meta property="og:image:width" content="288"/>
    <meta property="og:image:height" content="294"/>
    <?php /* END OF META */ ?>
    <?php /* FAVICON */ ?>
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/favicon/manifest.json">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    <?php /* END OF FAVICON */ ?>

    <?php $this->head() ?>
</head>
<body data-sa-theme="1">
<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/header.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Url;

?>

<div class="page-loader">
    <div class="page-loader__spinner">
        <svg viewBox="25 25 50 50">
            <circle cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
        </svg>
    </div>
</div>

<header class="header">
    <div class="navigation-trigger hidden-xl-up" data-sa-action="aside-open" data-sa-target=".sidebar">
        <i class="zmdi zmdi-menu"></i>
    </div>

    <div class="logo hidden-sm-down">
        <h1><a href="<?= Url::to(['site/index']) ?>">Luka Dobrota Camernik</a></h1>
    </div>
    <ul class="top-nav">
        <li class="hidden-xl-up"><a href="" data-sa-action="search-open"><i class="zmdi zmdi-search"></i></a></li>

        <li class="dropdown hidden-xs-down">
            <a href="" data-toggle="dropdown"><i class="zmdi zmdi-more-vert"></i></a>

            <div class="dropdown-menu dropdown-menu-right">
                <a href="" class="dropdown-item" data-sa-action="fullscreen">Fullscreen</a>
                <a href="" class="dropdown-item" data-sa-action="clear_local_storage">Clear Local Storage</a>
            </div>
        </li>

        <li class="hidden-xs-down">
            <a href="" class="top-nav__themes" data-sa-action="aside-open" data-sa-target=".themes"><i
                        class="zmdi zmdi-palette"></i></a>
        </li>
    </ul>
</header>

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);

// This variables repeat within the meta tags since some of them are for Facebook, OpenGraph and twitter cards.
$metaDescription = 'Portfolio and CV of Luka Dobrota Camernik.';
$metaTitle = 'PHP Backend Developer';
$metaImage = 'https://luka.camernik.com/img/luka.jpg';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" prefix="og: http://ogp.me/ns#">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>

    <?php /* META */ ?>
    <meta name="description" content="<?= $metaDescription ?>"/>
    <meta property="og:locale" content="en_GB"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://luka.camernik.com"/>
    <meta property="og:title" content="<?= $metaTitle ?>"/>
    <meta property="og:description" content="<?= $metaDescription ?>"/>
    <meta property="og:image" content="<?= $metaImage ?>"/>
    <meta property="og:image:width" content="288"/>
    <meta property="og:image:height" content="294"/>
    <?php /* END OF META */ ?>
    <?php /* FAVICON */ ?>
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/favicon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/favicon/manifest.json">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    <?php /* END OF FAVICON */ ?>

    <?php $this->head() ?>
</head>
<body data-sa-theme="7">
<?php $this->beginBody() ?>

<main class="main">
    <?= $this->render('header'); ?>
    <?= $this->render('sidebar'); ?>
    <section class="content">
        <?= $content ?>
    </section>
</main>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/sidebar.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Url;

$current = Yii::$app->requestedRoute;
?>

<aside class="sidebar">
    <div class="scrollbar-inner">

        <div class="user">
            <div class="user__info">
                <img class="user__img" src="/img/luka.jpg" alt="">
                <div>
                    <div class="user__name">Luka Dobrota Camernik</div>
                    <div class="user__email">luka.camernik@gmail.com</div>
                </div>
            </div>
        </div>

        <ul class="navigation">
            <li class="<?= $current === 'site/index' ? 'navigation__active' : '' ?>">
                <a href="<?= Url::to(['site/index']) ?>">
                    <i class="zmdi zmdi-home"></i> Profile
                </a>
            </li>
            <li class="<?= $current === 'site/skills' ? 'navigation__active' : '' ?>">
                <a href="<?= Url::to(['site/skills']) ?>">
                    <i class="zmdi zmdi-chart"></i> Skills
                </a>
            </li>
            <li class="<?= $current === 'site/projects' ? 'navigation__active' : '' ?>">
                <a href="<?= Url::to(['site/projects']) ?>">
                    <i class="zmdi zmdi-folder"></i> Projects
                </a>
            <li class="<?= $current === 'site/contact' ? 'navigation__active' : '' ?>">
                <a href="<?= Url::to(['site/contact']) ?>">
                    <i class="zmdi zmdi-email"></i> Contact
                </a>
            <li class="<?= $current === 'site/experience' ? 'navigation__active' : '' ?>">
                <a href="<?= Url::to(['site/experience']) ?>">
                    <i class="zmdi zmdi-globe"></i> Experiences
                </a>
            <li>
            <li class="<?= $current === 'site/faq' ? 'navigation__active' : '' ?>">
                <a href="<?= Url::to(['site/faq']) ?>">
                    <i class="zmdi zmdi-collection-bookmark"></i> FAQ
                </a>
            <li>
            <li>
                <a href="<?= Url::to(['site/cv']) ?>">
                    <i class="zmdi zmdi-view-list"></i> View CV
                </a>
            <li>
            <li>
                <a href="<?= Url::to(['site/download']) ?>">
                    <i class="zmdi zmdi-download"></i> Download CV
                </a>
            <li>
                <?php /*
            <li class="navigation__sub navigation__sub--active navigation__sub--toggled">
                <a href=""><i class="zmdi zmdi-collection-item"></i> Sample Pages</a>
                <ul>
                    <li class="navigation__active"><a href="profile-about.html">Profile</a></li>
                    <li class="navigation__active"><a href="messages.html">Messages</a></li>
                    <li class="@@contactsactive"><a href="contacts.html">Contacts</a></li>
                    <li class="@@newcontactsactive"><a href="new-contact.html">New Contact</a></li>
                    <li class="@@groupsactive"><a href="groups.html">Groups</a></li>
                    <li class="@@pricingtablesactive"><a href="pricing-tables.html">Pricing Tables</a></li>
                    <li class="@@invoiceactive"><a href="invoice.html">Invoice</a></li>
                    <li class="@@notesactive"><a href="notes.html">Notes</a></li>
                    <li class="@@searchresultsactive"><a href="search-results.html">Search Results</a></li>
                    <li class="@@issuesactive"><a href="issue-tracker.html">Issues Tracker</a></li>
                    <li class="@@faqactive"><a href="faq.html">FAQ</a></li>
                    <li class="@@teamactive"><a href="team.html">Team</a></li>
                    <li class="@@blogactive"><a href="blog.html">Blog</a></li>
                    <li class="@@blogdetailactive"><a href="blog-detail.html">Blog Detail</a></li>
                    <li class="@@qaactive"><a href="questions-answers.html">Questions & Answers</a></li>
                    <li class="@@qadetailactive"><a href="questions-answers-details.html">Questions & Answers
                            Details</a></li>
                    <li class="@@loginactive"><a href="login.html">Login & SignUp</a></li>
                    <li class="@@lockscreenactive"><a href="lockscreen.html">Lockscreen</a></li>
                    <li class="@@lockscreenactive"><a href="404.html">404</a></li>
                    <li class="@@emptyactive"><a href="empty.html">Empty Page</a></li>
                </ul>
            </li>
             */ ?>
        </ul>
    </div>
</aside>

<div class="themes">
    <div class="scrollbar-inner">
        <a href="" class="themes__item" data-sa-value="1"><img src="/img/bg/1.jpg" alt=""></a>
        <a href="" class="themes__item" data-sa-value="2"><img src="/img/bg/2.jpg" alt=""></a>
        <a href="" class="themes__item" data-sa-value="3"><img src="/img/bg/3.jpg" alt=""></a>
        <a href="" class="themes__item" data-sa-value="4"><img src="/img/bg/4.jpg" alt=""></a>
        <a href="" class="themes__item" data-sa-value="5"><img src="/img/bg/5.jpg" alt=""></a>
        <a href="" class="themes__item" data-sa-value="6"><img src="/img/bg/6.jpg" alt=""></a>
        <a href="" class="themes__item active" data-sa-value="7"><img src="/img/bg/7.jpg" alt=""></a>
        <a href="" class="themes__item" data-sa-value="8"><img src="/img/bg/8.jpg" alt=""></a>
        <a href="" class="themes__item" data-sa-value="9"><img src="/img/bg/9.jpg" alt=""></a>
        <a href="" class="themes__item" data-sa-value="10"><img src="/img/bg/10.jpg" alt=""></a>
    </div>
</div>